---
###########################################################################
# Heavily inspired by https://github.com/ElaoInfra/ansible-role-openvz.git
###########################################################################
- name: storage > Setup storages (except LVM)
  include: pvesm.yml
  with_items: '{{ proxmox_storages }}'
  when: item.type != 'lvm'

- name: storage > Setup LVM Volum Group on isci target
  lvg:
    vg: item.vg
    pvs: item.pvs
  with_items: '{{ proxmox_lvg_iscsi_config }}'

- name: storage > Setup storages (Only LVM)
  include: pvesm.yml
  with_items: '{{ proxmox_storages }}'
  when: item.type == 'lvm'
